### ISSUE TITLE
Updating configuration to "external component" version

### ISSUE THREAD

**Issue by cracrama** [maaad/RadSens1v2#10]
Hi 
Is it possible to update configuration of the sensor to "external components" version?
After recent update "custom component" is no longer supported in ESP. 
Please advise 
Kind regards.

**Comment by maaad** [comment]
Look at this repo: https://github.com/krbaker/esphome-radsens
```
external_components:
  - source: github://krbaker/esphome-radsens@v1.0.0
    components: [ radsens ]
    refresh: 600s

i2c:
  - id: bus_a
    frequency: 400kHz

radsens:

sensor:
  - platform: radsens
    dynamic_intensity:
      name: "Dynamic Intensity"
    static_intensity:
      name: "Static Intensity"
    counts_per_minute:
      name: "Counts Per Minute"
```
