### ISSUE TITLE
Help with CG-Anem

### ISSUE THREAD

**Issue by userosos** [maaad/RadSens1v2#9]
Hi! Can you help to me with CG-Anem sensor?
https://github.com/climateguard/CG-Anem/tree/master

```
esphome:
  name: esp-32c6
  friendly_name: esp-32c6
  libraries:
   - Wire
   - "ClimateGuard CG Anem"
#   - Arduino
#  includes:
   - cgAnem/cgAnem.h
#   - Arduino/arduino.h

esp32:
  board: esp32-c6-devkitc-1
  variant: ESP32C6
  framework:
    platform_version: https://github.com/stintel/platform-espressif32#esp32-c6-test
    type: esp-idf
    version: 5.1.1


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  password: ""

wifi:
  ssid: !secret 3_wifi_ssid
  password: !secret 3_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-32C6 Fallback Hotspot"
    password: ""

captive_portal:

i2c:
  - id: bus_a
    sda: GPIO19
    scl: GPIO21
    scan: true
  - id: bus_b
    sda: GPIO22
    scl: GPIO23
    scan: true

sensor:
- platform: custom
#  i2c_id: bus_a
#  address: 0x11
  lambda: |-
    auto cgAnem = new CG_Anem();
    App.register_component(cgAnem);
    return {cgAnem->temperature,cgAnem->airConsumption,cgAnem->airflowRate};
  sensors:
    - name: "Temperatura"
      id: CG_Anem_temperature
#      accuracy_decimals: 0.1
      unit_of_measurement: C
      state_class: measurement
    - name: "airConsumption"
      id: airConsumption
#      accuracy_decimals: 0.1
      unit_of_measurement: m^3/hour
      state_class: measurement
    - name: "airflowRate"
      id: airflowRate
#      accuracy_decimals: 0.1
      unit_of_measurement: m/s
      state_class: measurement

```
